openapi: 3.1.0
info:
  version: 1.0.0
  title: Contacts
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Contacts API
tags:
  - name: Contacts
    description: Operations with Contacts
  - name: Auth
    description: Operations with Auth
servers:
  - url: https://nodejs-hw-mongodb-3-rexi.onrender.com
paths:
  /contacts:
    post:
      $ref: ../swagger/path/contacts/post.yaml
    get:
      $ref: ../swagger/path/contacts/get.yaml
  /contacts/{id}:
    get:
      $ref: ../swagger/path/contacts/{id}/get.yaml
    patch:
      $ref: ../swagger/path/contacts/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/contacts/{id}/delete.yaml
components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
