openapi: 3.1.0
info:
  version: 1.0.0
  title: Podorozhnuky
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Podorozhnuky API
tags:
  - name: Stories
    description: Operations with Stories
  - name: Users
    description: Operations with Users
  - name: Auth
    description: Operations with Auth
servers:
  - url: https://travellers-back.onrender.com
paths:
  /users:
    get:
      $ref: ../swagger/path/users/get.yaml
  /users/{id}:
    get:
      $ref: ../swagger/path/users/{id}/get.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
