openapi: 3.1.0
info:
  version: 1.0.0
  title: Podorozhnuky
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  description: Podorozhnuky API

tags:
  - name: Stories
    description: Operations with Stories
  - name: Users
    description: Operations with Users
  - name: Auth
    description: Operations with Auth
  - name: Categories
    description: Operations with Categories

servers:
  - url: https://travellers-back.onrender.com

paths:
  /users:
    get:
      $ref: ../swagger/path/users/get.yaml
  /users/{id}:
    get:
      $ref: ../swagger/path/users/{id}/get.yaml

  /users/get-me:
    get:
      $ref: ../swagger/path/users/get-me/get.yaml

  /users/update-me:
    patch:
      $ref: ../swagger/path/users/update-me/patch.yaml
  /categories:
    get:
      $ref: ../swagger/path/categories/get.yaml

  /users/favourite/{id}:
    get:
      $ref: ../swagger/path/users/favourites/{id}/get.yaml
    post:
      $ref: ../swagger/path/users/favourites/{id}/post.yaml
    delete:
      $ref: ../swagger/path/users/favourites/{id}/delete.yaml

  /stories:
    get:
      $ref: ../swagger/path/stories/get.yaml
    post:
      $ref: ../swagger/path/stories/post.yaml
  /stories/my:
    get:
      $ref: ../swagger/path/stories/my.yaml
  /stories/{id}:
    get:
      $ref: ../swagger/path/stories/{id}/get.yaml
    patch:
      $ref: ../swagger/path/stories/{id}/patch.yaml
    delete:
      $ref: ../swagger/path/stories/{id}/delete.yaml

  /auth/register:
    post:
      $ref: ../swagger/path/auth/register.yaml
  /auth/login:
    post:
      $ref: ../swagger/path/auth/login.yaml
  /auth/refresh:
    post:
      $ref: ../swagger/path/auth/refresh.yaml
  /auth/logout:
    post:
      $ref: ../swagger/path/auth/logout.yaml

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
    cookieAuth:
      type: apiKey
      in: cookie
      name: accessToken

security:
  - bearerAuth: []
  - cookieAuth: []
